language: python

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.8-dev
  - nightly

matrix:
  fast_finish: true

install:
  - pip install codecov

script:
  - coverage run tests.py

after_success:
  - codecov
